grants-stack/packages/data-layer/src/data-layer.ts, grants-stack/packages/grant-explorer/src/features/api/keys.ts, grants-stack/packages/grant-explorer/src/features/api/maciCartUtils.ts, grants-stack/packages/grant-explorer/src/features/discovery/LandingPage.tsx, grants-stack/packages/grant-explorer/src/features/discovery/LandingTabs.tsx, grants-stack/packages/grant-explorer/src/features/projects/hooks/useRoundMaciMessages.ts, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx, grants-stack/packages/grant-explorer/src/index.tsx
=> Code cleanup

grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx
=> fix cart issues

grants-stack/packages/common/src/allo/abis/allo-v2/MACIQF.ts, grants-stack/packages/common/src/allo/backends/allo-v2.ts, grants-stack/packages/grant-explorer/src/checkoutStore.ts, grants-stack/packages/grant-explorer/src/constants/ZuzaluEvents.ts, grants-stack/packages/grant-explorer/src/features/api/types.ts, grants-stack/packages/grant-explorer/src/features/api/voting.ts, grants-stack/packages/grant-explorer/src/features/projects/hooks/useRoundMaciMessages.ts, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, grants-stack/packages/round-manager/src/constants.ts, grants-stack/packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx, grants-stack/packages/round-manager/src/features/round/RoundDetailForm.tsx
=> Frontend updates based on audit

grants-stack/packages/grant-explorer/src/checkoutStore.ts, grants-stack/packages/grant-explorer/src/features/contributors/DonationsTable.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> 38/update stats/linting

grants-stack/packages/common/src/allo/voting.ts, grants-stack/packages/common/src/allowlist.ts, grants-stack/packages/grant-explorer/src/checkoutStore.ts, grants-stack/packages/grant-explorer/src/features/api/voting.ts, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
1. Prevent sending the Proof of attendance proof in that case
2. Render a message that outlines Zupas reuse and the Limit of non allowlisted users
=> check is a zupass is already used in a round

grants-stack/packages/data-layer/src/data-layer.ts, grants-stack/packages/data-layer/src/queries.ts, grants-stack/packages/grant-explorer/src/features/projects/hooks/useRoundMaciMessages.ts, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> add stat cards

grants-stack/packages/common/src/allo/backends/allo-v2.ts, grants-stack/packages/common/src/allo/voting.ts, grants-stack/packages/data-layer/src/data-layer.ts, grants-stack/packages/data-layer/src/queries.ts, grants-stack/packages/grant-explorer/src/checkoutStore.ts, grants-stack/packages/grant-explorer/src/features/api/types.ts, grants-stack/packages/grant-explorer/src/features/projects/hooks/useRoundMaciMessages.ts, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
1. Don't contribute once donation step rejected => **tryAgain**
2. Don't contribute again when contribution happened => donationFailed => Page reloaded => Submit Donation
=> fixed resubmit donations if prev failed

grants-stack/packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
=> failed loading project

grants-stack/packages/common/src/allo/backends/allo-v2.ts, grants-stack/packages/round-manager/src/stores/createRoundStore.ts
=> core: prevent txn from hanging on reject

grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/Header.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
=> Cart UI updates

grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
- Make link evident
- Ensure add to cart is hidden once donated
- increase donation input size
=> chore: fixes

grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/store.ts
=> Storage read/write Contribution amount

grants-stack/packages/grant-explorer/src/features/contributors/DonationsTable.tsx, grants-stack/packages/grant-explorer/src/features/projects/hooks/useRoundMaciMessages.ts
=> added voice credits and ETH improved in general

grants-stack/packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, grants-stack/packages/grant-explorer/src/store.ts
Fix cart bugs.
fixes: #94 
fixes: #128
=> fix: cart bugs

grants-stack/packages/builder/src/utils/chains.ts, grants-stack/packages/grant-explorer/src/app/chainConfig.ts, grants-stack/packages/grant-explorer/src/features/discovery/LandingPage.tsx, grants-stack/packages/round-manager/src/app/wagmi.ts
Remove sepolia rounds from prod
=> remove sepolia rounds from prod

grants-stack/packages/builder/src/components/rounds/Show.tsx, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Update application end date in rounds
=> update application end date in rounds

grants-stack/packages/round-manager/src/features/api/exports.ts
fix csv download issue in manager
=> fix: csv download issue in manager

grants-stack/packages/builder/src/components/rounds/Show.tsx
=> Revert "feat: enable applications on builder"

grants-stack/packages/common/src/allo/allo.ts, grants-stack/packages/common/src/allo/backends/allo-v2.ts, grants-stack/packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx
Issue Fixed
The problem was that data was not being passed to the children Allo function, resulting in latestUpdateAt always being set to 0.
Solution
- Passed the necessary data to the function.
- Ensured latestUpdateAt is updated correctly based on the provided data.
=> fixed review

grants-stack/packages/builder/src/utils/chains.ts, grants-stack/packages/common/src/allo/backends/allo-v2.ts, grants-stack/packages/grant-explorer/src/app/chainConfig.ts, grants-stack/packages/round-manager/src/app/wagmi.ts
=> feat: add optimism to ui

grants-stack/packages/builder/src/components/rounds/Show.tsx, grants-stack/packages/grant-explorer/src/app/chainConfig.ts, grants-stack/packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Remove application end time condition
=> chore: remove application end time condition

grants-stack/packages/builder/src/utils/chains.ts, grants-stack/packages/grant-explorer/src/app/chainConfig.ts, grants-stack/packages/round-manager/src/app/wagmi.ts
This reverts commit 4319ace7352f157eabc49fcf8261fce0d6779ad9.
=> Revert "chore(MACI): include sepolia in maci grandstack (#158)"

grants-stack/packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
To avoid collusion we can either merge to remove the donation history
Or 
To start working on change donations feature
=> remove donation history

grants-stack/packages/builder/src/actions/acceptOwnership.ts, grants-stack/packages/builder/src/actions/grantsMetadata.ts, grants-stack/packages/builder/src/actions/projects.ts, grants-stack/packages/builder/src/components/base/Preview.tsx, grants-stack/packages/builder/src/components/base/StatusModal.tsx, grants-stack/packages/builder/src/components/base/acceptOwnershipButton.tsx, grants-stack/packages/builder/src/components/grants/Details.tsx, grants-stack/packages/builder/src/components/grants/ProjectDetailsHeader.tsx, grants-stack/packages/builder/src/components/grants/Show.tsx, grants-stack/packages/builder/src/reducers/acceptOwnership.ts, grants-stack/packages/builder/src/reducers/index.ts, grants-stack/packages/builder/src/reducers/projects.ts, grants-stack/packages/builder/src/utils/steps.ts, grants-stack/packages/common/src/allo/allo.ts, grants-stack/packages/common/src/allo/backends/allo-v1.ts, grants-stack/packages/common/src/allo/backends/allo-v2.ts
Allow previous Scroll owners to take ownership of their migrated profiles on Optimism
=> added transfer ownership functionality
